---
 - Cluster: 'SFF Preperation'
   Coordinates: '100,0,241,53'
   Customization: Standard
   IsRequired: 0
 - Cluster: 'Assembly Step'
   Coordinates: '95,139,244,192'
   Customization: Standard
   IsRequired: 1
 - Cluster: 'Hawkeye Step'
   Coordinates: '96,279,245,333'
   Customization: Standard
   IsRequired: 0
