---
 - Name: 'Celera Assembly'
   Description: 'An assembly pipeline using the Celera Assembler.  This pipeline can accept multiple inputs from multiple libraries in SFF format.  The first step converts the SFF file to FRG files for use by the Celera Assembler.  This is followed by the assembly step.  The final step is to create the necessary files for use with Hawkeye to visualize the assembly.'
   Status: Published
   SubClass: CeleraAssembly::Jun2010
   Version: 1
   Release: 'Jun 2010'
   Image: '/include/img/assembly-pipeline.png'
   Layout: |
     <commandSetRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="commandSet.xsd" type="instance">
      <commandSet type="serial">
        <state>incomplete</state>
        <name>start</name>
        <commandSet type="parallel">
            <state>incomplete</state>
           ___SFF Preperation___ 
        </commandSet>
        ___Assembly Step___
        ___Hawkeye Step___
      </commandSet>
     </commandSetRoot>
