---
 - Name: 'Methyl Seq Analysis Pipeline'
   Description: '<p>The Methyl Seq Analysis Pipeline maps bisulfite-treated short reads using the BS Seeker software.</p>'
   Status: Published
   SubClass: MethylSeq
   Version: 1
   Release: 'Nov 2010'
   Image: '/include/img/methyl_seq.png'
   Layout: |
     <commandSetRoot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="commandSet.xsd" type="instance">
         <commandSet type="serial">
             <state>incomplete</state>
             <name>start</name>
             <commandSet type="serial">
                 <state>incomplete</state>
                ___Map Bisulfite-treated Reads___
                ___Convert Output___
             </commandSet>
         </commandSet>
     </commandSetRoot>
